package dev.runtime_lab.flowit.domain.notification.dto;

public enum NotificationAlertType {
	TASK_CREATED,
	TASK_DATE_CHANGED,
	TASK_STATUS_CHANGED,
	TASK_PROGRESS_CHANGED,
	TASK_ASSIGNED,
	TASK_UNASSIGNED,
	WORKSPACE_MEMBER_JOINED,
	WORKSPACE_MEMBER_ROLE_CHANGED,
	WORKSPACE_MEMBER_REMOVED,
	WORKSPACE_ACCESS_REVOKED,
	WORKSPACE_MEMBER_WITHDRAWN
}
